# Generated by Django 5.0.7 on 2024-07-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='Log',
            new_name='log',
        ),
    ]
