# Generated by Django 5.0.7 on 2024-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('project_name', models.CharField(max_length=250)),
                ('log', models.TextField(verbose_name='Log')),
                ('state', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-created'],
            },
        ),
    ]
