# Generated by Django 5.0.7 on 2024-07-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'ordering': ['project_name'], 'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
        migrations.RemoveField(
            model_name='registry',
            name='log',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='state',
        ),
        migrations.AddField(
            model_name='registry',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='registry',
            name='Log',
            field=models.TextField(default=None, verbose_name='Log'),
        ),
    ]
