# Generated by Django 5.0.7 on 2024-07-17 09:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='phone',
            field=models.CharField(default=None, max_length=9, validators=[core.models.validate_phone], verbose_name='Teléfono'),
        ),
    ]
