# Generated by Django 5.0.7 on 2024-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registry_email_registry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(blank=True, default='provwork@gmail.com', max_length=254, null=True),
        ),
    ]
