# Generated by Django 5.0.7 on 2024-07-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(default='provwork@gmail.com', max_length=254),
        ),
    ]
