# Generated by Django 5.0.7 on 2024-07-17 09:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(blank=True, default='provwork@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='phone',
            field=models.CharField(default=123456789, max_length=9, validators=[core.models.validate_phone], verbose_name='Teléfono'),
        ),
    ]
