# Generated by Django 5.0.7 on 2024-07-17 09:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registry_email_alter_registry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(default='provwork@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='phone',
            field=models.CharField(default=123456789, max_length=9, unique=True, validators=[core.models.validate_phone], verbose_name='Teléfono'),
        ),
    ]
