# Generated by Django 5.0.7 on 2024-07-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_registry_email_alter_registry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='phone',
        ),
    ]
