# Generated by Django 5.0.7 on 2024-07-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tfl',
            field=models.CharField(max_length=9),
        ),
    ]
