# Generated by Django 5.0.7 on 2024-07-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_tfl_profile_tlf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
